services:
  redis:
    image: redis:7-alpine
    container_name: webhook_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: webhook_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"
      CACHE_URL: "redis://redis:6379/1"
      DELIVERY_LOG_URL: "redis://redis:6379/2"

  worker:
    build: .
    container_name: webhook_worker
    command: rq worker webhooks
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"
      CACHE_URL: "redis://redis:6379/1"
      DELIVERY_LOG_URL: "redis://redis:6379/2"
